package Vista;

import Excepciones.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Alejandra Oteiza
 */
public class Panel extends javax.swing.JPanel {

    private static boolean valido;
    
    public Panel() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNumAlbaran = new javax.swing.JTextField();
        cMin = new javax.swing.JComboBox();
        cHora2 = new javax.swing.JComboBox();
        cMin2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cHora = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        bBorrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        tfNumAlbaran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNumAlbaranFocusLost(evt);
            }
        });

        cMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cMin.setSelectedIndex(-1);

        cHora2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cHora2.setSelectedIndex(-1);

        cMin2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cMin2.setSelectedIndex(-1);

        jLabel2.setText("TIEMPO IDA:");

        cHora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cHora.setSelectedIndex(-1);

        jLabel3.setText("TIEMPO VUELTA:");

        bBorrar.setText("Borrar Alabarán");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        jLabel4.setText(":");

        jLabel5.setText(":");

        jLabel1.setText("Albaran");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNumAlbaran, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(cHora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cMin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bBorrar)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNumAlbaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cHora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cMin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBorrar)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
       VistaAlbaran.dropRow(this);
    }//GEN-LAST:event_bBorrarActionPerformed

    private void tfNumAlbaranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNumAlbaranFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumAlbaranFocusLost

    public boolean validateAll(){
        try{
            validateNumAlb();
            validateHoras();
        //validateMinutos();
        valido = true;
        }
        catch(AlbEmpty e){
            JOptionPane.showMessageDialog(null, "EL número de albarán es obligatorio.");
            valido = false;
        }
        catch(HoraNoSelected e){
            JOptionPane.showMessageDialog(null, "La hora de llegada y la hora de salida son obligatorias.");
            valido = false;
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e);
            valido = false;
        }
        
        return valido;
    }
    
    private void validateNumAlb() throws Exception{
        if (tfNumAlbaran.getText().isEmpty()) {
            throw new AlbEmpty();
        }
    }
    
    private void validateHoras() throws Exception{
        if (cHora.getSelectedIndex() == -1 || cHora2.getSelectedIndex() == -1 || cMin.getSelectedIndex() == -1 || cMin2.getSelectedIndex() == -1) {
            throw new HoraNoSelected();
        }
    }
    
    public JTextField getNumAlbaran(){
        return tfNumAlbaran;
    }
    
    public JComboBox getHora(){
        return cHora;
    }
    
    public JComboBox getHora2(){
        return cHora2;
    }
    
    public JComboBox getMin(){
        return cMin;
    }
    
    public JComboBox getMin2(){
        return cMin2;
    }
    
    /*public static int getIndexHora(){
        return cHora.getSelectedIndex();
    }
    
    public static int getIndexHora2(){
        return cHora2.getSelectedIndex();
    }
    
    public static int getIndexMin(){
        return cMin.getSelectedIndex();
    }
    
    public static int getIndexMin2(){
        return cMin2.getSelectedIndex();
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JComboBox cHora;
    private javax.swing.JComboBox cHora2;
    private javax.swing.JComboBox cMin;
    private javax.swing.JComboBox cMin2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfNumAlbaran;
    // End of variables declaration//GEN-END:variables
}
