package Vista;

import controlador.Controlador;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author Alejandra Oteiza
 */

public class VenAlbara extends javax.swing.JFrame {
    private static final Dimension THUMB_SIZE = new Dimension(170, 150);
    private Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
    private static JPanel thumbPanel = new JPanel(new GridLayout(0, 1, 5, 5));
    
    private static ArrayList<Panel> rows = new ArrayList();
    private static boolean panelValidado;
    
    public VenAlbara()throws HeadlessException{
        initComponents();
        setLocationRelativeTo(null);
        
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(thumbPanel, BorderLayout.NORTH);
        setLayout(new BorderLayout());
        add(new JScrollPane(jPanel2), BorderLayout.CENTER);
        
        
    }
    
    @Override
    public Dimension getPreferredSize() {
       return new Dimension(screen.width / 10 * 6, screen.height / 10 * 6);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmAddAlbaran = new javax.swing.JMenu();
        jmSave = new javax.swing.JMenu();
        jmClose = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        jmAddAlbaran.setText("Añadir Albarán");
        jmAddAlbaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAddAlbaranMouseClicked(evt);
            }
        });
        jMenuBar2.add(jmAddAlbaran);

        jmSave.setText("Guadar Cambios");
        jmSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSaveMouseClicked(evt);
            }
        });
        jMenuBar2.add(jmSave);

        jmClose.setText("Cerrar Parte");
        jMenuBar2.add(jmClose);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAddAlbaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAddAlbaranMouseClicked
        addRow();
        revalidate();
        repaint();
    }//GEN-LAST:event_jmAddAlbaranMouseClicked
    
    private void addRow(){
        //panel.setSize(50, 100);
        //panel.setLocation(5, n);
        int i = rows.size();
        
        if (i == 0) {
            Panel panel = new Panel();
            thumbPanel.add(panel);
            thumbPanel.revalidate();
            thumbPanel.repaint();
            rows.add(panel);
        }else{
            panelValidado = validatePanel(rows.get(i-1));
            
            if (panelValidado) {
                Panel panel = new Panel();
                thumbPanel.add(panel);
                thumbPanel.revalidate();
                thumbPanel.repaint();
                rows.add(panel);
            }   
        }
    }
    
    public static boolean validatePanel(Panel panel){
        return panel.validateAll();
    }
    
    public static void dropRow(JPanel panel){
        thumbPanel.remove(panel);
        thumbPanel.revalidate();
        thumbPanel.repaint();
        rows.remove(panel);
        
    }
    
    private void jmSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSaveMouseClicked
        try {
            Controlador.saveRows(rows);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jmSaveMouseClicked
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenAlbara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenAlbara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenAlbara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenAlbara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenAlbara().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu jmAddAlbaran;
    private javax.swing.JMenu jmClose;
    private javax.swing.JMenu jmSave;
    // End of variables declaration//GEN-END:variables
}
