/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import centros.trabajadores.Main;

/**
 *
 * @author andrés
 */
public class VistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mTrabajador = new javax.swing.JMenu();
        mCentro = new javax.swing.JMenu();
        mParte = new javax.swing.JMenu();
        miAdmin = new javax.swing.JMenuItem();
        miLogis = new javax.swing.JMenuItem();
        mAlbaran = new javax.swing.JMenu();
        mInforme = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        mTrabajador.setText("Trabajador");
        mTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mTrabajadorMouseClicked(evt);
            }
        });
        jMenuBar1.add(mTrabajador);

        mCentro.setText("Centro");
        mCentro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mCentroMouseClicked(evt);
            }
        });
        jMenuBar1.add(mCentro);

        mParte.setText("Partes");

        miAdmin.setText("Administrador");
        mParte.add(miAdmin);

        miLogis.setText("Logistica");
        mParte.add(miLogis);

        jMenuBar1.add(mParte);

        mAlbaran.setText("Albaranes");
        jMenuBar1.add(mAlbaran);

        mInforme.setText("Informe");
        mInforme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mInformeMouseClicked(evt);
            }
        });
        jMenuBar1.add(mInforme);

        mSalir.setText("Salir");
        mSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mInformeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mInformeMouseClicked
        Main.abrirInforme();
    }//GEN-LAST:event_mInformeMouseClicked

    private void mTrabajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mTrabajadorMouseClicked
        Main.irVT();
    }//GEN-LAST:event_mTrabajadorMouseClicked

    private void mCentroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mCentroMouseClicked
        Main.irVC();
    }//GEN-LAST:event_mCentroMouseClicked

    private void mSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSalirMouseClicked
        Main.volverALogin(this);
    }//GEN-LAST:event_mSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mAlbaran;
    private javax.swing.JMenu mCentro;
    private javax.swing.JMenu mInforme;
    private javax.swing.JMenu mParte;
    private javax.swing.JMenu mSalir;
    private javax.swing.JMenu mTrabajador;
    private javax.swing.JMenuItem miAdmin;
    private javax.swing.JMenuItem miLogis;
    // End of variables declaration//GEN-END:variables
}
