CREATE OR REPLACE PACKAGE PAC_TRABAJADOR IS
  TYPE G_CURSOR IS REF CURSOR;
  PROCEDURE get_trabajador(i_dniTrab IN TRABAJADORES.DNI%TYPE, o_cursor OUT G_CURSOR);
  PROCEDURE get_trabajadores_centro(i_idCen IN CENTROS.IDCENTRO%TYPE, o_cursor OUT G_CURSOR);
  PROCEDURE get_tipos_centro(i_tipo IN TIPOTRABAJADORES.TIPO%TYPE, o_cursor OUT G_CURSOR);
  PROCEDURE get_trabajador_usuario(i_usuario IN LOGINS.USUARIO%TYPE, i_pass IN LOGINS.PASS%TYPE, o_cursor OUT G_CURSOR);
  PROCEDURE get_trabajador_extra(i_idTrab IN TRABAJADORES.IDTRABAJADOR%TYPE, o_idCentro OUT TRABAJADORES.IDCENTRO%TYPE, o_user OUT LOGINS.USUARIO%TYPE, o_pass OUT LOGINS.PASS%TYPE);
END PAC_TRABAJADOR;

CREATE OR REPLACE PACKAGE BODY PAC_TRABAJADOR IS
  
  PROCEDURE get_trabajador(
    i_dniTrab IN TRABAJADORES.DNI%TYPE, o_cursor OUT G_CURSOR
  )AS
  BEGIN
    OPEN o_cursor for
      SELECT IDTRABAJADOR, IDCENTRO, DNI, NOMBRE, APE1, APE2, FECHANAC, 
             SALARIO, MOVILEMP, TLFPERSONAL, CALLE, PORTAL, PISO, MANO, 
             (SELECT TIPO FROM TIPOTRABAJADORES WHERE IDTIPO = T.IDTIPO) TIPO
      FROM TRABAJADORES T
      WHERE DNI = i_dniTrab;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20105, 'NO SE ENCONTRÓ EL TRABAJADORES');
  END;
  
  PROCEDURE get_trabajadores_centro(
    i_idCen IN CENTROS.IDCENTRO%TYPE, o_cursor OUT G_CURSOR
  )AS
  BEGIN
    OPEN o_cursor for
      SELECT IDTRABAJADOR
      FROM TRABAJADORES
      WHERE IDCENTRO = i_idCen;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20105, 'NO SE ENCONTRARON TRABAJADORES DE ESE CENTRO');
  END;
  
  PROCEDURE get_tipos_centro(
    i_tipo IN TIPOTRABAJADORES.TIPO%TYPE, o_cursor OUT G_CURSOR
  )AS
  BEGIN
    OPEN o_cursor for
      SELECT IDTRABAJADOR
      FROM TRABAJADORES
      WHERE IDTIPO = (SELECT IDTIPO FROM TIPOTRABAJADORES WHERE UPPER(TIPO) LIKE UPPER(i_tipo));
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20105, 'NO SE ENCONTRÓ EL TRABAJADOR');
  END;
  
  PROCEDURE get_trabajador_usuario(
    i_usuario IN LOGINS.USUARIO%TYPE, i_pass IN LOGINS.PASS%TYPE, o_cursor OUT G_CURSOR
  )AS
  BEGIN
    OPEN o_cursor for
    SELECT *
    FROM TRABAJADORES
    WHERE idLogin = (SELECT idLogin FROM LOGINS WHERE USUARIO LIKE i_usuario AND PASS LIKE i_pass);
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20105, 'NO SE ENCONTRÓ EL USUARIO');
  END;
  
  
  PROCEDURE get_trabajador_extra(
  i_idTrab IN TRABAJADORES.IDTRABAJADOR%TYPE, o_idCentro OUT TRABAJADORES.IDCENTRO%TYPE, o_user OUT LOGINS.USUARIO%TYPE, o_pass OUT LOGINS.PASS%TYPE
  )AS
  BEGIN
    SELECT T.IDCENTRO,L.USUARIO,L.PASS INTO o_idCentro, o_user, o_pass
    FROM TRABAJADORES T, LOGINS L
    WHERE T.IDTRABAJADOR = i_idTrab
    AND T.IDLOGIN = L.IDLOGIN;
  END;
  
END PAC_TRABAJADOR;